export enum ERROR {
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNDEFINED = 'UNDEFINED',
  INCORRECT_LOGIN_OR_PASSWORD = 'INCORRECT_LOGIN_OR_PASSWORD',
  USER_WITH_SAME_LOGIN_IS_EXISTING = 'USER_WITH_SAME_LOGIN_IS_EXISTING',
  HAVE_NO_PERMISSIONS = 'HAVE_NO_PERMISSIONS',

  AREA_CREATION_ERROR = 'AREA_CREATION_ERROR',
  DISTRICT_CREATION_ERROR = 'DISTRICT_CREATION_ERROR',
  POPULATED_AREA_CREATION_ERROR = 'POPULATED_AREA_CREATION_ERROR',
  LOCATION_IN_POPULATED_AREA_CREATION_ERROR = 'LOCATION_IN_POPULATED_AREA_CREATION_ERROR',
  ADDRESS_NUMBER_CREATION_ERROR = 'ADDRESS_NUMBER_CREATION_ERROR',
}

export type PossibleErrorCodes = keyof typeof ERROR;