export enum ERROR {
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNDEFINED = 'UNDEFINED',
  INCORRECT_LOGIN_OR_PASSWORD = 'INCORRECT_LOGIN_OR_PASSWORD',
  USER_WITH_SAME_LOGIN_IS_EXISTING = 'USER_WITH_SAME_LOGIN_IS_EXISTING',
  HAVE_NO_PERMISSIONS = 'HAVE_NO_PERMISSIONS',
}
